# Generated by Django 5.0 on 2024-12-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_message_is_read_message_is_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='read_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
