# Generated by Django 5.0 on 2024-12-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sentmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedmessage',
            name='original_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
